DROP TABLE domains;
CREATE TABLE domains (id INTEGER PRIMARY KEY AUTOINCREMENT, domain TEXT, last_crawled TEXT);
DROP TABLE links;
CREATE TABLE links (id INTEGER PRIMARY KEY AUTOINCREMENT, domain_id INTEGER, link TEXT);
